### ISSUE TITLE
Submit to packagist.org?

### ISSUE THREAD

**Issue by Taitava** [lekoala/silverstripe-chosenfield#2]
Hi,

I just noticed that I can't install this module via composer because it doesn't exist in packagist.org. I ended up downloading the module manually as a temporary solution, but I would still like to switch to composer. :)

And if you do that, can you also create a release in github so it's easier to lock into a specific version in composer?

Thanks! This is a nice module. :)

**Comment by lekoala** [comment]
done. i don't use this module anymore, but still if it helps, i'm happy to help

**Comment by Taitava** [comment]
Thanks! :)
